export const CHATBOT_FORM_VALIDATION = {
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 50,
  DESCRIPTION_MIN_LENGTH: 10,
  DESCRIPTION_MAX_LENGTH: 3500, // ~500 words at average 6 chars/word + spaces
  DESCRIPTION_MIN_WORDS: 2,
  DESCRIPTION_MAX_WORDS: 500,
  PERSONA_MIN_LENGTH: 20,
  PERSONA_MAX_LENGTH: 2000,
  INSTRUCTIONS_MIN_LENGTH: 20,
  INSTRUCTIONS_MAX_LENGTH: 3000,
  WELCOME_MESSAGE_MIN_LENGTH: 1,
  WELCOME_MESSAGE_MAX_LENGTH: 200,
} as const;

export const CHATBOT_FILE_UPLOAD = {
  MAX_THUMBNAIL_SIZE_MB: 5,
  MAX_THUMBNAIL_SIZE_BYTES: 5 * 1024 * 1024,
  ALLOWED_IMAGE_TYPES: ["image/jpeg", "image/png", "image/gif"] as const,
} as const;
